version: '3.9'
networks:
  backend:


services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app
    networks:
      - backend
  python:
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - db
    networks:
      - backend